"""
Lines to be displayed on the help screen.
"""
help_lines = [
    ['Navigation:',                     ''],
    ['    Up/Down or k/j',              'Move up/down'],
    ['    p/n',                         'Previous/Next page'],
    ['    P/N',                         'First/Last page'],
    ['    g or home',                   'Go to top of page'],
    ['    G or end',                    'Go to bottom of page'],
    ['Selection:',                      ''],
    ['    Space',                       'Toggle selection'],
    ['    m or C-a',                    'Select all'],
    ['    M or C-r',                    'Deselect all'],
    ['    v',                           'Start and stop visual selection'],
    ['    V',                           'Start and stop visual deselection'],
    ['    l/Enter',                     'Submit selection'],
    ['Sorting:',                        ''],
    ['    1-9',                         'Select column (1-based index)'],
    ['    s',                           'Cycle sort method'],
    ['    t',                           'Toggle sort order'],
    ['Filter or search rows (regexp):',                    ''],
    ['    f',                           'Begin filtering rows'],
    ['    /',                           'Begin searching rows'],
    ['      --[1-9]',                   'Specify column'],
    ['      --i',                       'Make match case sensitive'],
    ['      --v',                       'Invert filter'],
    ['Columns:',                         ''],
    ['    Shift+1-9',                   'Hide/show column'],
    ['    [/]',                         'Increase/Decrease column width'],
    ['    {',                           'Move column left'],
    ['    }',                           'Move column right'],
    ['Clipboard:',                      ''],
    ['    y',                           'Copy selected indices to clipboard (tsv)'],
    ['    Y',                           'Copy visible parts of selected indices to clipboard (tsv)'],
    ['    c',                           'Copy selected entries to clipboard (python list)'],
    ['Misc:',                           ''],
    ['    ?',                           'Show this help screen'],
    ['    :',                           'Specify user optios to be returned with selection'],
    ['    \\',                          'Clear settings'],
    ['Settings:',                           ''],
    ['    `',                           'settings input'],
    ['      !\\d+',                       'Show/hide column'],
    ['      !r',                          'toggle auto refresh'],
    ['      o',                           'Open submenu'],
    ['      +',                           'Increase lines per page'],
    ['      -',                           'Decrease lines per page'],
    ['      -',                           'Decrease lines per page'],
]
