import curses

"""

Define colour options for list_picker, help, and notification

"""

def get_colours(pick:int=0) -> dict[str, int]:
    """ Define colour options for list_picker. """
    colours = [
    {
        'background': 232,
        'normal_fg': 253,
        'unselected_fg': 253,
        'unselected_bg': 232,
        'cursor_fg': 253,
        'cursor_bg': 25,
        'selected_fg': 253,
        'selected_bg': 135,
        'header_fg': 232,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 25,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 40,
        'title_fg': 232,
        'title_bg': 40,
        'scroll_bar_bg': 247,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 25,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    },
    {
        'background': 232,
        'normal_fg': curses.COLOR_WHITE,
        'unselected_fg': curses.COLOR_WHITE,
        'cursor_fg': curses.COLOR_WHITE,
        'cursor_bg': 27,
        'selected_fg': curses.COLOR_WHITE,
        'header_fg': 232,
        'unselected_bg': 232,
        'selected_bg': 25,
        'header_bg': curses.COLOR_WHITE,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': curses.COLOR_GREEN,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': curses.COLOR_WHITE,
        'active_input_bg': 25,
        'active_input_fg': curses.COLOR_WHITE,
        'modes_selected_fg': curses.COLOR_WHITE,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 15,
        'title_bar':           208,
        'title_fg': 232,
        'title_bg': 208,
    },
    {
        'background': curses.COLOR_WHITE,
        'normal_fg': curses.COLOR_BLACK,
        'unselected_fg': curses.COLOR_BLACK,
        'cursor_fg': curses.COLOR_WHITE,
        'selected_fg': curses.COLOR_BLACK,
        'header_fg': curses.COLOR_WHITE,
        'unselected_bg': curses.COLOR_WHITE,
        'selected_bg': curses.COLOR_BLUE,
        'cursor_bg': curses.COLOR_BLUE,
        'header_bg': curses.COLOR_BLACK,
        'error_bg': curses.COLOR_WHITE,
        'error_fg': curses.COLOR_RED,
        'complete_bg': curses.COLOR_WHITE,
        'complete_fg': curses.COLOR_GREEN,
        'waiting_bg': curses.COLOR_WHITE,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': curses.COLOR_WHITE,
        'active_fg': curses.COLOR_BLUE,
        'paused_bg': curses.COLOR_BLACK,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': curses.COLOR_WHITE,
        'search_bg': 162,
        'active_input_bg': 25,
        'active_input_fg': 232,
        'modes_selected_fg': curses.COLOR_WHITE,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': curses.COLOR_WHITE,
    },
    {
        'background': 232,
        'normal_fg': curses.COLOR_WHITE,
        'unselected_fg': curses.COLOR_WHITE,
        'cursor_fg': curses.COLOR_BLACK,
        'selected_fg': curses.COLOR_WHITE,
        'header_fg': 232,
        'unselected_bg': 232,
        'selected_bg': 69,
        'cursor_bg': 69,
        'header_bg': 76,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': curses.COLOR_GREEN,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': curses.COLOR_BLUE,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': curses.COLOR_WHITE,
        'search_bg': 162,
        'active_input_bg': 25,
        'active_input_fg': 232,
        'modes_selected_fg': curses.COLOR_WHITE,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': curses.COLOR_WHITE,
    },
    {
        'background': curses.COLOR_BLACK,
        'normal_fg': curses.COLOR_GREEN,
        'unselected_fg': curses.COLOR_WHITE,
        'cursor_fg': curses.COLOR_BLACK,
        'selected_fg': curses.COLOR_YELLOW,
        'header_fg': curses.COLOR_BLACK,
        'unselected_bg': curses.COLOR_BLACK,
        'selected_bg': 9,
        'cursor_bg': 9,
        'header_bg': curses.COLOR_YELLOW,
        'error_bg': curses.COLOR_BLACK,
        'error_fg': curses.COLOR_RED,
        'complete_bg': curses.COLOR_BLACK,
        'complete_fg': curses.COLOR_GREEN,
        'waiting_bg': curses.COLOR_BLACK,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': curses.COLOR_BLACK,
        'active_fg': curses.COLOR_BLUE,
        'paused_bg': curses.COLOR_BLACK,
        'paused_fg': 244,
        'search_bg': 166,
        'search_fg': curses.COLOR_GREEN,
        'search_bg': 166,
        'active_input_bg': 25,
        'active_input_fg': 232,
        'modes_selected_fg': curses.COLOR_WHITE,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': curses.COLOR_WHITE,
    },
    {
        'background': curses.COLOR_BLACK,
        'normal_fg': curses.COLOR_GREEN,
        'unselected_fg': curses.COLOR_WHITE,
        'cursor_fg': curses.COLOR_WHITE,
        'selected_fg': curses.COLOR_YELLOW,
        'header_fg': curses.COLOR_BLACK,
        'unselected_bg': curses.COLOR_BLACK,
        'selected_bg': 165,
        'cursor_bg': 165,
        'header_bg': 198,
        'error_bg': curses.COLOR_BLACK,
        'error_fg': curses.COLOR_RED,
        'complete_bg': curses.COLOR_BLACK,
        'complete_fg': curses.COLOR_GREEN,
        'waiting_bg': curses.COLOR_BLACK,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': curses.COLOR_BLACK,
        'active_fg': curses.COLOR_BLUE,
        'paused_bg': curses.COLOR_BLACK,
        'paused_fg': 244,
        'search_bg': 166,
        'search_fg': curses.COLOR_GREEN,
        'search_bg': 166,
        'active_input_bg': 25,
        'active_input_fg': 232,
        'modes_selected_fg': curses.COLOR_WHITE,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': curses.COLOR_WHITE,
    },
    ]
    for colour in colours:
        colour["20pc_bg"] = colour["background"]
        colour["40pc_bg"] = colour["background"]
        colour["60pc_bg"] = colour["background"]
        colour["80pc_bg"] = colour["background"]
        colour["100pc_bg"] = colour["background"]
        colour["error_bg"] = colour["background"]
        colour["complete_bg"] = colour["background"]
        colour["waiting_bg"] = colour["background"]
        colour["active_bg"] = colour["background"]
        colour["paused_bg"] = colour["background"]
        colour["paused_bg"] = colour["background"]
        # colour["search_bg"] = colour["background"]
    return colours[pick]


help_colours = {
        'background': 232,
        'normal_fg': 253,
        'unselected_fg': 253,
        'cursor_fg': 253,
        'cursor_bg': 232,
        'selected_fg': 253,
        'header_fg': 232,
        'unselected_bg': 232,
        'selected_bg': 25,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 25,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar':           40,
        'title_fg': 232,
        'title_bg': 40,
        'scroll_bar_bg': 247,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 25,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    }
notification_colours = {
        'background': 25,
        'normal_fg': 253,
        'unselected_fg': 253,
        'unselected_bg': 25,
        'cursor_fg': 253,
        'cursor_bg': 25,
        'selected_fg': 253,
        'selected_bg': 25,
        'header_fg': 232,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 25,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 40,
        'title_fg': 232,
        'title_bg': 40,
        'scroll_bar_bg': 247,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 25,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    }
