import curses

"""
Define colour options for list_picker, help, and notification
"""

def get_colours(pick:int=0) -> dict[str, int]:
    """ Define colour options for list_picker. """
    colours = [
        ### Green header, blue cursor, blue modes, 
    {
        'background': 232,
        'normal_fg': 253,
        'unselected_fg': 253,
        'unselected_bg': 232,
        'cursor_fg': 253,
        'cursor_bg': 25,
        'selected_fg': 253,
        'selected_bg': 135,
        'header_fg': 232,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 28,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 28,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 28,
        'title_fg': 253,
        'title_bg': 28,
        'scroll_bar_bg': 247,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 28,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    },
        ### Black and white
    {
        'background': 232,
        'normal_fg': 253,
        'unselected_bg': 232,
        'unselected_fg': 253,
        'cursor_bg': 253,
        'cursor_fg': 232,
        'selected_bg': 253,
        'selected_fg': 232,
        'header_bg': 253,
        'header_fg': 232,
        'error_bg': 232,
        'error_fg': 253,
        'complete_bg': 232,
        'complete_fg': 253,
        'waiting_bg': 232,
        'waiting_fg': 253,
        'active_bg': 232,
        'active_fg': 253,
        'paused_bg': 232,
        'paused_fg': 253,
        'search_bg': 253,
        'search_fg': 232,
        'active_input_bg': 232,
        'active_input_fg': 253,
        'modes_selected_bg': 253,
        'modes_selected_fg': 232,
        'modes_unselected_bg': 232,
        'modes_unselected_fg': 253,
        'title_bar': 232,
        'title_bg': 253,
        'title_fg': 232,
        'scroll_bar_bg': 253,
        'selected_header_column_bg': 232,
        'selected_header_column_fg': 253,
        'footer_bg': 253,
        'footer_fg': 232,
        'refreshing_bg': 253,
        'refreshing_fg': 232,
        '40pc_fg': 253,
        '40pc_bg': 232,
    },
    ]
    for colour in colours:
        colour["20pc_bg"] = colour["background"]
        colour["40pc_bg"] = colour["background"]
        colour["60pc_bg"] = colour["background"]
        colour["80pc_bg"] = colour["background"]
        colour["100pc_bg"] = colour["background"]
        colour["error_bg"] = colour["background"]
        colour["complete_bg"] = colour["background"]
        colour["waiting_bg"] = colour["background"]
        colour["active_bg"] = colour["background"]
        colour["paused_bg"] = colour["background"]
        colour["paused_bg"] = colour["background"]
        # colour["search_bg"] = colour["background"]
    if pick > len(colours) - 1:
        return colours[0]
    return colours[pick]

def get_help_colours(pick: int=0) -> dict:
    colours = [
    { # Black and white, gray cursor, green title
        'background': 232,
        'normal_fg': 253,
        'unselected_fg': 253,
        'cursor_fg': 253,
        'cursor_bg': 235,
        'selected_fg': 253,
        'header_fg': 232,
        'unselected_bg': 232,
        'selected_bg': 25,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 28,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 28,
        'title_fg': 253,
        'title_bg': 28,
        'scroll_bar_bg': 247,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 28,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    },
    { # Black and white, gray cursor, black and white title
        'background': 232,
        'normal_fg': 253,
        'unselected_fg': 253,
        'cursor_fg': 253,
        'cursor_bg': 235,
        'selected_fg': 253,
        'header_fg': 232,
        'unselected_bg': 232,
        'selected_bg': 25,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 244,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 25,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 25,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 232,
        'title_bg': 253,
        'title_fg': 232,
        'scroll_bar_bg': 253,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 25,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    }
    ]
    if pick > len(colours) - 1:
        return colours[0]
    return colours[pick]

def get_notification_colours(pick:int=0) -> dict:
    colours = [
    { # Green title, gray background, black text
        'background': 237,
        'normal_fg': 253,
        'unselected_fg': 253,
        'unselected_bg': 237,
        'cursor_fg': 253,
        'cursor_bg': 237,
        'selected_fg': 253,
        'selected_bg': 237,
        'header_fg': 232,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 237,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 28,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 237,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 28,
        'title_fg': 253,
        'title_bg': 28,
        'scroll_bar_bg': 247,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 28,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    },
    { # Black and white
        'background': 237,
        'normal_fg': 253,
        'unselected_fg': 253,
        'unselected_bg': 237,
        'cursor_fg': 253,
        'cursor_bg': 237,
        'selected_fg': 253,
        'selected_bg': 237,
        'header_fg': 232,
        'header_bg': 253,
        'error_bg': 232,
        'error_fg': curses.COLOR_RED,
        'complete_bg': 232,
        'complete_fg': 82,
        'waiting_bg': 232,
        'waiting_fg': curses.COLOR_YELLOW,
        'active_bg': 232,
        'active_fg': 33,
        'paused_bg': 232,
        'paused_fg': 237,
        'search_bg': 162,
        'search_fg': 253,
        'active_input_bg': 237,
        'active_input_fg': 253,
        'modes_selected_fg': 253,
        'modes_selected_bg': 237,
        'modes_unselected_fg': 232,
        'modes_unselected_bg': 253,
        'title_bar': 232,
        'title_bg': 253,
        'title_fg': 232,
        'scroll_bar_bg': 253,
        'selected_header_column_fg': 232,
        'selected_header_column_bg': 247,
        'footer_fg': 232,
        'footer_bg': 253,
        'refreshing_fg': 237,
        'refreshing_bg': 253,
        '40pc_fg': 166,
        '40pc_bg': 232,
    }
    ]

    if pick > len(colours) - 1:
        return colours[0]
    return colours[pick]
